const json=(data,status=200,origin='*')=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','access-control-allow-origin':origin,'access-control-allow-methods':'GET,POST,PUT,DELETE,OPTIONS','access-control-allow-headers':'content-type,authorization','cache-control':'no-store'}});
const DAY_MS=86400000,SESSION_DAYS=365,PASSWORD_ITERATIONS=100000;
const EMPTY_STATE={drones:[],pilots:[],flights:[],tasks:[],plants:[]};
const ROLE_STATE_KEYS={admin:['drones','pilots','flights','tasks','plants'],pilot:['flights','tasks','plants'],technician:['drones','tasks','plants'],user:[]};
const VALID_ROLES=['admin','pilot','technician','user'];
const parseRoles=value=>[...new Set((Array.isArray(value)?value:String(value||'').split(',')).map(role=>String(role).trim().toLowerCase()).filter(role=>VALID_ROLES.includes(role)))];
function normalizeRoles(value,fallback='user'){const roles=parseRoles(value);if(!roles.length)roles.push(...parseRoles(fallback));if(roles.length>1)return roles.filter(role=>role!=='user');return roles.length?roles:['user'];}
const hasRole=(user,role)=>normalizeRoles(user?.roles||user?.role).includes(role);
const primaryRole=roles=>roles.includes('admin')?'admin':roles[0]||'user';
function allowedOrigin(request,env){const origin=request.headers.get('origin')||'*';if(!env.ALLOWED_ORIGIN||env.ALLOWED_ORIGIN==='*')return'*';return origin===env.ALLOWED_ORIGIN?origin:env.ALLOWED_ORIGIN;}
async function readBody(request){try{return await request.json();}catch{return null;}}
async function sha256(value){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function normalizeEmail(v){return String(v||'').trim().toLowerCase();}
function normalizeCode(v){return String(v||'').normalize('NFKC').trim().toUpperCase().replace(/[‐‑‒–—−]/g,'-').replace(/\s+/g,'').replace(/-/g,'');}
function validCompanyEmail(email,env){const domain=String(env.AUTH_DOMAIN||'dronetech.cz').trim().toLowerCase();return email.endsWith(`@${domain}`)&&email.length<=254;}
function validPassword(v){return typeof v==='string'&&v.length>=10&&v.length<=128;}
function validPin(v){return typeof v==='string'&&/^\d{6}$/.test(v);}
function randomCode(){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',bytes=crypto.getRandomValues(new Uint8Array(8)),raw=[...bytes].map(v=>alphabet[v%alphabet.length]).join('');return`${raw.slice(0,4)}-${raw.slice(4)}`;}
function b64(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s);}
function unb64(value){const raw=atob(value);return Uint8Array.from(raw,c=>c.charCodeAt(0));}
async function hashPassword(password,salt=crypto.getRandomValues(new Uint8Array(16))){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations:PASSWORD_ITERATIONS},key,256);return{hash:b64(new Uint8Array(bits)),salt:b64(salt)};}
async function verifyPassword(password,salt,hash){if(!salt||!hash)return false;return(await hashPassword(password,unb64(salt))).hash===hash;}
async function addColumn(env,sql){try{await env.DB.prepare(sql).run();}catch(e){if(!String(e).toLowerCase().includes('duplicate column'))throw e;}}
async function ensureSchema(env){await env.DB.batch([env.DB.prepare(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,name TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',active INTEGER NOT NULL DEFAULT 1,phone TEXT,position TEXT,profile_note TEXT,access_code_hash TEXT,password_hash TEXT,password_salt TEXT,pin_hash TEXT,pin_salt TEXT,pin_failures INTEGER NOT NULL DEFAULT 0,pin_locked_until TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_login TEXT)`),env.DB.prepare(`CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)`),env.DB.prepare(`CREATE TABLE IF NOT EXISTS chat_messages(id TEXT PRIMARY KEY,author TEXT NOT NULL,message TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,sender_id TEXT,recipient_id TEXT)`),env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token_hash)')]);await addColumn(env,'ALTER TABLE users ADD COLUMN access_code_hash TEXT');await addColumn(env,'ALTER TABLE users ADD COLUMN password_hash TEXT');await addColumn(env,'ALTER TABLE users ADD COLUMN password_salt TEXT');await addColumn(env,'ALTER TABLE users ADD COLUMN pin_hash TEXT');await addColumn(env,'ALTER TABLE users ADD COLUMN pin_salt TEXT');await addColumn(env,'ALTER TABLE users ADD COLUMN pin_failures INTEGER NOT NULL DEFAULT 0');await addColumn(env,'ALTER TABLE users ADD COLUMN pin_locked_until TEXT');await addColumn(env,'ALTER TABLE users ADD COLUMN phone TEXT');await addColumn(env,'ALTER TABLE users ADD COLUMN position TEXT');await addColumn(env,'ALTER TABLE users ADD COLUMN profile_note TEXT');await addColumn(env,'ALTER TABLE chat_messages ADD COLUMN sender_id TEXT');await addColumn(env,'ALTER TABLE chat_messages ADD COLUMN recipient_id TEXT');}
async function createSession(user,env){const token=`${crypto.randomUUID()}${crypto.randomUUID()}`.replace(/-/g,''),expiresAt=new Date(Date.now()+SESSION_DAYS*DAY_MS).toISOString();await env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,?)').bind(crypto.randomUUID(),user.id,await sha256(token),expiresAt).run();return{token,expiresAt};}
async function getSessionUser(request,env){const auth=request.headers.get('authorization')||'';if(!auth.startsWith('Bearer '))return null;const token=auth.slice(7).trim();if(!token)return null;const row=await env.DB.prepare(`SELECT u.id,u.email,u.name,u.role,u.active,u.phone,u.position,u.profile_note,u.password_hash,s.id AS session_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>CURRENT_TIMESTAMP AND u.active=1`).bind(await sha256(token)).first();if(!row)return null;const expiresAt=new Date(Date.now()+SESSION_DAYS*DAY_MS).toISOString();await env.DB.prepare('UPDATE sessions SET last_seen=CURRENT_TIMESTAMP,expires_at=? WHERE id=?').bind(expiresAt,row.session_id).run();const roles=normalizeRoles(row.role);return{id:row.id,email:row.email,name:row.name,role:primaryRole(roles),roles,phone:row.phone||'',position:row.position||'',profileNote:row.profile_note||'',sessionId:row.session_id,hasPassword:Boolean(row.password_hash)};}
const publicUser=u=>{const roles=normalizeRoles(u.roles||u.role);return{id:u.id,email:u.email,name:u.name,role:primaryRole(roles),roles,phone:u.phone||'',position:u.position||'',profileNote:u.profile_note??u.profileNote??'',hasPassword:Boolean(u.password_hash??u.hasPassword)}};
export default{async fetch(request,env){const origin=allowedOrigin(request,env);if(request.method==='OPTIONS')return json({ok:true},200,origin);try{await ensureSchema(env);const url=new URL(request.url);
if(url.pathname==='/health'&&request.method==='GET'){const count=await env.DB.prepare('SELECT COUNT(*) AS total FROM users').first();return json({ok:true,initialized:Number(count?.total||0)>0,auth:'invite-activation-user-pin-admin-password'},200,origin);}
if(url.pathname==='/auth/bootstrap'&&request.method==='POST'){const count=await env.DB.prepare('SELECT COUNT(*) AS total FROM users').first();if(Number(count?.total||0)>0)return json({error:'Aplikace už byla inicializována.'},409,origin);const body=await readBody(request),email=normalizeEmail(body?.email),name=String(body?.name||'').trim().slice(0,100),code=normalizeCode(body?.code);if(!validCompanyEmail(email,env)||!name||code.length<6)return json({error:'Vyplňte jméno, firemní e-mail a startovací kód.'},400,origin);if(!normalizeCode(env.BOOTSTRAP_CODE)||code!==normalizeCode(env.BOOTSTRAP_CODE))return json({error:'Nesprávný startovací kód administrátora.'},401,origin);const user={id:crypto.randomUUID(),email,name,role:'admin',hasPassword:false};await env.DB.prepare(`INSERT INTO users(id,email,name,role,last_login) VALUES(?,?,?,'admin',CURRENT_TIMESTAMP)`).bind(user.id,email,name).run();return json({...await createSession(user,env),user:publicUser(user)},201,origin);}
if(url.pathname==='/auth/code-login'&&request.method==='POST')return json({error:'Je dostupná nová verze DFM. Zavřete aplikaci, znovu ji otevřete a potom použijte pozvánku.'},426,origin);
if(url.pathname==='/auth/activate'&&request.method==='POST'){const body=await readBody(request),email=normalizeEmail(body?.email),code=normalizeCode(body?.code),pin=String(body?.pin||''),codeHash=await sha256(code),user=await env.DB.prepare('SELECT id,email,name,role,active,access_code_hash,password_hash FROM users WHERE email=?').bind(email).first();if(!validPin(pin))return json({error:'PIN musí obsahovat přesně 6 číslic.'},400,origin);if(!user||!user.active||!user.access_code_hash||codeHash!==user.access_code_hash)return json({error:'Pozvánka není platná, už byla použita nebo byla nahrazena novou.'},401,origin);const pwd=await hashPassword(pin),changed=await env.DB.prepare('UPDATE users SET access_code_hash=NULL,pin_hash=?,pin_salt=?,pin_failures=0,pin_locked_until=NULL,last_login=CURRENT_TIMESTAMP WHERE id=? AND access_code_hash=?').bind(pwd.hash,pwd.salt,user.id,codeHash).run();if(!changed.meta?.changes)return json({error:'Pozvánka už byla použita.'},409,origin);return json({...await createSession(user,env),user:publicUser(user)},200,origin);}
if(url.pathname==='/auth/pin-login'&&request.method==='POST'){const body=await readBody(request),email=normalizeEmail(body?.email),pin=String(body?.pin||''),user=await env.DB.prepare('SELECT id,email,name,role,active,password_hash,pin_hash,pin_salt,pin_failures,pin_locked_until FROM users WHERE email=?').bind(email).first();if(!user||!user.active||!user.pin_hash||!validPin(pin))return json({error:'Nesprávný e-mail nebo PIN.'},401,origin);if(user.pin_locked_until&&new Date(user.pin_locked_until)>new Date())return json({error:'Příliš mnoho chybných pokusů. Zkuste to znovu za 15 minut.'},429,origin);if(!await verifyPassword(pin,user.pin_salt,user.pin_hash)){const failures=Number(user.pin_failures||0)+1,locked=failures>=5?new Date(Date.now()+15*60*1000).toISOString():null;await env.DB.prepare('UPDATE users SET pin_failures=?,pin_locked_until=? WHERE id=?').bind(failures>=5?0:failures,locked,user.id).run();return json({error:locked?'Příliš mnoho chybných pokusů. Přihlášení bylo na 15 minut zablokováno.':'Nesprávný e-mail nebo PIN.'},locked?429:401,origin);}await env.DB.prepare('UPDATE users SET pin_failures=0,pin_locked_until=NULL,last_login=CURRENT_TIMESTAMP WHERE id=?').bind(user.id).run();return json({...await createSession(user,env),user:publicUser(user)},200,origin);}
if(url.pathname==='/auth/admin-login'&&request.method==='POST'){const body=await readBody(request),email=normalizeEmail(body?.email),password=String(body?.password||''),user=await env.DB.prepare('SELECT id,email,name,role,active,password_hash,password_salt FROM users WHERE email=?').bind(email).first();if(!user||!user.active||!hasRole(user,'admin')||!await verifyPassword(password,user.password_salt,user.password_hash))return json({error:'Nesprávný administrátorský e-mail nebo heslo.'},401,origin);await env.DB.prepare('UPDATE users SET last_login=CURRENT_TIMESTAMP WHERE id=?').bind(user.id).run();return json({...await createSession(user,env),user:publicUser(user)},200,origin);}
const currentUser=await getSessionUser(request,env);if(!currentUser)return json({error:'Přihlášení je vyžadováno.'},401,origin);
if(url.pathname==='/auth/me'&&request.method==='GET')return json({user:publicUser(currentUser)},200,origin);
if(url.pathname==='/auth/profile'&&request.method==='PUT'){const body=await readBody(request),name=String(body?.name||'').trim().slice(0,100),phone=String(body?.phone||'').trim().slice(0,40),position=String(body?.position||'').trim().slice(0,100),profileNote=String(body?.profileNote||'').trim().slice(0,500);if(!name)return json({error:'Jméno je povinné.'},400,origin);await env.DB.prepare('UPDATE users SET name=?,phone=?,position=?,profile_note=? WHERE id=?').bind(name,phone,position,profileNote,currentUser.id).run();return json({ok:true,user:publicUser({...currentUser,name,phone,position,profileNote})},200,origin);}
if(url.pathname==='/auth/logout'&&request.method==='POST'){await env.DB.prepare('DELETE FROM sessions WHERE id=?').bind(currentUser.sessionId).run();return json({ok:true},200,origin);}
if(url.pathname==='/auth/admin-password'&&request.method==='POST'){if(!hasRole(currentUser,'admin'))return json({error:'Heslo lze nastavit pouze administrátorovi.'},403,origin);const body=await readBody(request),password=String(body?.password||'');if(!validPassword(password))return json({error:'Heslo musí mít alespoň 10 znaků.'},400,origin);const pwd=await hashPassword(password);await env.DB.prepare('UPDATE users SET password_hash=?,password_salt=? WHERE id=?').bind(pwd.hash,pwd.salt,currentUser.id).run();return json({ok:true},200,origin);}
if(url.pathname==='/admin/users'&&request.method==='GET'){if(!hasRole(currentUser,'admin'))return json({error:'Pouze administrátor.'},403,origin);const rows=await env.DB.prepare(`SELECT u.id,u.email,u.name,u.role,u.active,u.created_at,u.last_login,u.access_code_hash IS NOT NULL AS invite_ready,u.password_hash IS NOT NULL AS has_password,COUNT(s.id) AS sessions,MAX(s.last_seen) AS last_seen FROM users u LEFT JOIN sessions s ON s.user_id=u.id AND s.expires_at>CURRENT_TIMESTAMP GROUP BY u.id ORDER BY u.name`).all();return json({users:(rows.results||[]).map(user=>({...publicUser({...user,hasPassword:user.has_password}),active:user.active,created_at:user.created_at,last_login:user.last_login,invite_ready:user.invite_ready,has_password:user.has_password,sessions:user.sessions,last_seen:user.last_seen}))},200,origin);}
if(url.pathname==='/admin/users'&&request.method==='POST'){if(!hasRole(currentUser,'admin'))return json({error:'Pouze administrátor.'},403,origin);const body=await readBody(request),email=normalizeEmail(body?.email),name=String(body?.name||'').trim().slice(0,100),roles=normalizeRoles(body?.roles||body?.role),role=roles.join(',');if(!validCompanyEmail(email,env)||!name)return json({error:'Vyplňte jméno a e-mail @dronetech.cz.'},400,origin);if(await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())return json({error:'Uživatel s tímto e-mailem už existuje.'},409,origin);const accessCode=randomCode(),id=crypto.randomUUID();await env.DB.prepare('INSERT INTO users(id,email,name,role,access_code_hash) VALUES(?,?,?,?,?)').bind(id,email,name,role,await sha256(normalizeCode(accessCode))).run();return json({ok:true,user:publicUser({id,email,name,roles}),accessCode},201,origin);}
if(url.pathname.startsWith('/admin/users/')&&url.pathname.endsWith('/regenerate-code')&&request.method==='POST'){if(!hasRole(currentUser,'admin'))return json({error:'Pouze administrátor.'},403,origin);const id=decodeURIComponent(url.pathname.slice('/admin/users/'.length,-'/regenerate-code'.length)),target=await env.DB.prepare('SELECT id,email,name,role,password_hash FROM users WHERE id=?').bind(id).first();if(!target)return json({error:'Uživatel nebyl nalezen.'},404,origin);const accessCode=randomCode();await env.DB.batch([env.DB.prepare('UPDATE users SET access_code_hash=?,pin_hash=NULL,pin_salt=NULL,pin_failures=0,pin_locked_until=NULL WHERE id=?').bind(await sha256(normalizeCode(accessCode)),id),env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(id)]);return json({ok:true,user:publicUser(target),accessCode},200,origin);}
if(url.pathname.startsWith('/admin/users/')&&url.pathname.endsWith('/logout')&&request.method==='POST'){if(!hasRole(currentUser,'admin'))return json({error:'Pouze administrátor.'},403,origin);const id=decodeURIComponent(url.pathname.slice('/admin/users/'.length,-'/logout'.length));if(id===currentUser.id)return json({error:'Vlastní relaci ukončete tlačítkem Odhlásit se.'},400,origin);await env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(id).run();return json({ok:true},200,origin);}
if(url.pathname.startsWith('/admin/users/')&&request.method==='DELETE'){if(!hasRole(currentUser,'admin'))return json({error:'Pouze administrátor.'},403,origin);const id=decodeURIComponent(url.pathname.slice('/admin/users/'.length));if(id===currentUser.id)return json({error:'Nemůžete smazat vlastní účet.'},400,origin);const target=await env.DB.prepare('SELECT id,role FROM users WHERE id=?').bind(id).first();if(!target)return json({error:'Uživatel nebyl nalezen.'},404,origin);if(hasRole(target,'admin')){const rows=await env.DB.prepare('SELECT role FROM users WHERE active=1').all(),admins=(rows.results||[]).filter(user=>hasRole(user,'admin')).length;if(admins<=1)return json({error:'Posledního aktivního administrátora nelze smazat.'},400,origin);}await env.DB.batch([env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(id),env.DB.prepare('DELETE FROM users WHERE id=?').bind(id)]);return json({ok:true},200,origin);}
if(url.pathname.startsWith('/admin/users/')&&request.method==='PUT'){if(!hasRole(currentUser,'admin'))return json({error:'Pouze administrátor.'},403,origin);const id=decodeURIComponent(url.pathname.slice('/admin/users/'.length)),body=await readBody(request),name=String(body?.name||'').trim().slice(0,100),roles=normalizeRoles(body?.roles||body?.role),role=roles.join(','),active=body?.active?1:0;if(!name)return json({error:'Jméno je povinné.'},400,origin);if(id===currentUser.id&&!active)return json({error:'Nemůžete deaktivovat vlastní účet.'},400,origin);if(id===currentUser.id&&!roles.includes('admin'))return json({error:'Nemůžete odebrat administrátorskou funkci vlastnímu účtu.'},400,origin);await env.DB.prepare('UPDATE users SET name=?,role=?,active=? WHERE id=?').bind(name,role,active,id).run();if(!active)await env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(id).run();return json({ok:true},200,origin);}
if(url.pathname==='/state'&&request.method==='GET'){const row=await env.DB.prepare('SELECT data,updated_at FROM app_state WHERE id=1').first();return json({data:row?JSON.parse(row.data):EMPTY_STATE,updatedAt:row?.updated_at||null},200,origin);}
if(url.pathname==='/state'&&request.method==='PUT'){const body=await readBody(request);if(!body||typeof body.data!=='object')return json({error:'Invalid state payload'},400,origin);const allowedKeys=[...new Set(normalizeRoles(currentUser.roles||currentUser.role).flatMap(role=>ROLE_STATE_KEYS[role]||[]))];if(!allowedKeys.length)return json({error:'Tato role může data pouze prohlížet.'},403,origin);const row=await env.DB.prepare('SELECT data FROM app_state WHERE id=1').first();const existing=row?JSON.parse(row.data):structuredClone(EMPTY_STATE);const incoming=body.data||{};const merged={...existing};for(const key of allowedKeys)merged[key]=Array.isArray(incoming[key])?incoming[key]:[];const encoded=JSON.stringify(merged);if(encoded.length>2000000)return json({error:'State is too large'},413,origin);await env.DB.prepare(`INSERT INTO app_state(id,data,updated_at) VALUES(1,?,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=CURRENT_TIMESTAMP`).bind(encoded).run();return json({ok:true,data:merged},200,origin);}
if(url.pathname==='/chat'&&request.method==='GET'){const rows=await env.DB.prepare('SELECT id,author,message,created_at,sender_id,recipient_id FROM chat_messages WHERE recipient_id IS NULL OR sender_id=? OR recipient_id=? ORDER BY created_at DESC LIMIT 300').bind(currentUser.id,currentUser.id).all();return json({messages:(rows.results||[]).reverse()},200,origin);}
if(url.pathname==='/chat'&&request.method==='POST'){const body=await readBody(request),message=String(body?.message||'').trim().slice(0,2000),recipientId=String(body?.recipientId||'').trim()||null;if(!message)return json({error:'Zpráva je prázdná.'},400,origin);if(recipientId){if(recipientId===currentUser.id)return json({error:'Nelze založit chat s vlastním účtem.'},400,origin);const recipient=await env.DB.prepare('SELECT id FROM users WHERE id=? AND active=1').bind(recipientId).first();if(!recipient)return json({error:'Vybraný příjemce nebyl nalezen.'},404,origin);}const id=crypto.randomUUID();await env.DB.prepare('INSERT INTO chat_messages(id,author,message,sender_id,recipient_id) VALUES(?,?,?,?,?)').bind(id,currentUser.name||currentUser.email,message,currentUser.id,recipientId).run();return json({ok:true,id},201,origin);}
return json({error:'Not found'},404,origin);}catch(error){console.error(error);return json({error:'Cloud API error'},500,origin);}}};
