import React,{useEffect,useMemo,useRef,useState}from'react';
import{BarcodeFormat,EncodeHintType,QRCodeWriter}from'@zxing/library';
import AppV2 from'./AppV2';
import'./cloud-shell.css';

const STORAGE_KEY='dfm_react_pwa_v1',SESSION_KEY='dfm_auth_session',PENDING_KEY='dfm_pending_sync';
const API='https://dfm-cloud-api.bednarik.workers.dev';
const APP_URL='https://lukas1212890.github.io/DFM-v2/';
const EMPTY={drones:[],pilots:[],flights:[],tasks:[]};
const roleLabel=r=>({admin:'Administrátor',pilot:'Pilot',technician:'Technik',user:'Uživatel'}[r]||'Uživatel');
const ROLE_PERMISSIONS={
 admin:{editDrones:true,editPilots:true,editFlights:true,editTasks:true,deleteRecords:true,manageUsers:true},
 pilot:{editDrones:false,editPilots:false,editFlights:true,editTasks:true,deleteRecords:false,manageUsers:false},
 technician:{editDrones:true,editPilots:false,editFlights:false,editTasks:true,deleteRecords:false,manageUsers:false},
 user:{editDrones:false,editPilots:false,editFlights:false,editTasks:false,deleteRecords:false,manageUsers:false}
};
const toBase64Url=value=>btoa(unescape(encodeURIComponent(value))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const fromBase64Url=value=>decodeURIComponent(escape(atob(value.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(value.length/4)*4,'='))));
const inviteLink=(email,code)=>`${APP_URL}#invite=${toBase64Url(JSON.stringify({email,code}))}`;
function qrSvg(text,size=180){try{const hints=new Map();hints.set(EncodeHintType.MARGIN,1);const matrix=new QRCodeWriter().encode(text,BarcodeFormat.QR_CODE,size,size,hints);let path='';for(let y=0;y<matrix.getHeight();y++)for(let x=0;x<matrix.getWidth();x++)if(matrix.get(x,y))path+=`M${x} ${y}h1v1h-1z`;return`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${matrix.getWidth()} ${matrix.getHeight()}" shape-rendering="crispEdges"><rect width="100%" height="100%" fill="white"/><path d="${path}" fill="black"/></svg>`;}catch{return'';}}

export default function CloudShell(){
 const[token,setToken]=useState(()=>localStorage.getItem(SESSION_KEY)||'');
 const[auth,setAuth]=useState('checking'),[initialized,setInitialized]=useState(true),[pinAuth,setPinAuth]=useState(false),[user,setUser]=useState(null);
 const[email,setEmail]=useState(''),[name,setName]=useState(''),[code,setCode]=useState(''),[activation,setActivation]=useState(null),[pin2,setPin2]=useState('');
 const[loginMode,setLoginMode]=useState('code'),[password,setPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[password2,setPassword2]=useState('');
 const[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('Připojuji…');
 const[profileOpen,setProfileOpen]=useState(false),[usersOpen,setUsersOpen]=useState(false),[passwordOpen,setPasswordOpen]=useState(false);
 const[users,setUsers]=useState([]),[newUser,setNewUser]=useState({name:'',email:'',role:'user'}),[inviteCard,setInviteCard]=useState(null),[adminError,setAdminError]=useState('');
 const[chatOpen,setChatOpen]=useState(false),[messages,setMessages]=useState([]),[message,setMessage]=useState('');
 const lastRemote=useRef(''),syncing=useRef(false),saveTimer=useRef(null),autoInviteDone=useRef(false);
 const request=async(path,options={},needsAuth=true)=>{const headers={'content-type':'application/json',...(needsAuth&&token?{authorization:`Bearer ${token}`}:{})};const response=await fetch(`${API}${path}`,{...options,headers:{...headers,...(options.headers||{})}});let payload={};try{payload=await response.json();}catch{}if(!response.ok){const e=new Error(payload.error||`Cloud odpověděl ${response.status}`);e.status=response.status;throw e;}return payload;};
 const applySession=r=>{localStorage.setItem(SESSION_KEY,r.token);setToken(r.token);setUser(r.user);setAuth('ready');setStatus('Online');history.replaceState(null,'',location.pathname+location.search);setTimeout(()=>location.reload(),80);};
 const clearSession=()=>{localStorage.removeItem(SESSION_KEY);setToken('');setUser(null);setAuth('login');setCode('');setPassword('');};
 const loginWith=(loginEmail,credential,usePin=pinAuth)=>request(usePin?'/auth/pin-login':'/auth/code-login',{method:'POST',body:JSON.stringify(usePin?{email:loginEmail,pin:credential}:{email:loginEmail,code:credential})},false);

 useEffect(()=>{(async()=>{try{const h=await request('/health',{},false),supportsPin=h.auth==='invite-activation-user-pin-admin-password';setInitialized(Boolean(h.initialized));setPinAuth(supportsPin);const match=location.hash.match(/^#invite=(.+)$/);if(match&&!token&&!autoInviteDone.current){autoInviteDone.current=true;try{const data=JSON.parse(fromBase64Url(match[1]));if(!data.email||!data.code)throw new Error('Pozvánka nemá platný formát.');setEmail(data.email);if(supportsPin){setActivation(data);setAuth('activate');}else applySession(await loginWith(data.email,data.code,false));return;}catch(e){history.replaceState(null,'',location.pathname+location.search);setError(e.message||'Pozvánku se nepodařilo použít.');setAuth('login');return;}}if(!token){setAuth('login');return;}try{const r=await request('/auth/me');setUser(r.user);setAuth('ready');setStatus(navigator.onLine?'Online':'Offline');}catch(e){if(!navigator.onLine){setAuth('ready');setStatus('Offline');}else throw e;}}catch(e){if(e.status===401)clearSession();else if(token){setAuth('ready');setStatus('Offline');}else setAuth('offline');}})();},[]);
 const login=async e=>{e.preventDefault();setBusy(true);setError('');try{let r;if(!initialized)r=await request('/auth/bootstrap',{method:'POST',body:JSON.stringify({email,name,code})},false);else if(loginMode==='password')r=await request('/auth/admin-login',{method:'POST',body:JSON.stringify({email,password})},false);else r=await loginWith(email,code);applySession(r);}catch(e){setError(e.message);}finally{setBusy(false);}};
 const activate=async e=>{e.preventDefault();setError('');if(!/^\d{6}$/.test(code)){setError('PIN musí obsahovat přesně 6 číslic.');return;}if(code!==pin2){setError('Zadané PINy se neshodují.');return;}setBusy(true);try{const r=await request('/auth/activate',{method:'POST',body:JSON.stringify({email:activation.email,code:activation.code,pin:code})},false);setActivation(null);setPin2('');applySession(r);}catch(e){setError(e.message);}finally{setBusy(false);}};
 const logout=async()=>{try{await request('/auth/logout',{method:'POST'});}catch{}clearSession();};
 const saveAdminPassword=async e=>{e.preventDefault();setAdminError('');if(newPassword!==password2){setAdminError('Hesla se neshodují.');return;}try{await request('/auth/admin-password',{method:'POST',body:JSON.stringify({password:newPassword})});setUser({...user,hasPassword:true});setNewPassword('');setPassword2('');setPasswordOpen(false);alert('Administrátorské heslo bylo uloženo.');}catch(e){setAdminError(e.message);}};

 const pushState=async data=>{if(!token||syncing.current)return;try{setStatus('Synchronizuji…');await request('/state',{method:'PUT',body:JSON.stringify({data})});lastRemote.current=JSON.stringify(data||EMPTY);localStorage.removeItem(PENDING_KEY);setStatus('Online');}catch(e){if(e.status===401&&navigator.onLine)clearSession();else{localStorage.setItem(PENDING_KEY,'1');setStatus('Offline · čeká na synchronizaci');}}};
 const syncNow=async()=>{if(!navigator.onLine||!token)return;await pushState(JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')||EMPTY);};
 useEffect(()=>{if(auth!=='ready'||!token)return;const original=Storage.prototype.setItem;const initial=async()=>{if(!navigator.onLine){setStatus(localStorage.getItem(PENDING_KEY)?'Offline · čeká na synchronizaci':'Offline');return;}try{if(localStorage.getItem(PENDING_KEY)){await syncNow();return;}const r=await request('/state'),remote=r.data||EMPTY,local=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')||EMPTY;if(JSON.stringify(remote)!==JSON.stringify(local)){syncing.current=true;original.call(localStorage,STORAGE_KEY,JSON.stringify(remote));syncing.current=false;location.reload();}lastRemote.current=JSON.stringify(remote);setStatus('Online');}catch{setStatus('Offline');}};initial();Storage.prototype.setItem=function(k,v){original.call(this,k,v);if(this===localStorage&&k===STORAGE_KEY&&!syncing.current){original.call(localStorage,PENDING_KEY,'1');setStatus(navigator.onLine?'Čeká na synchronizaci':'Offline · čeká na synchronizaci');clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>{try{pushState(JSON.parse(v));}catch{}},500);}};const online=()=>syncNow(),offline=()=>setStatus(localStorage.getItem(PENDING_KEY)?'Offline · čeká na synchronizaci':'Offline');addEventListener('online',online);addEventListener('offline',offline);return()=>{Storage.prototype.setItem=original;removeEventListener('online',online);removeEventListener('offline',offline);clearTimeout(saveTimer.current);};},[auth,token]);

 const loadUsers=async()=>{try{setUsers((await request('/admin/users')).users||[]);}catch(e){setAdminError(e.message);}};
 const openUsers=async()=>{setProfileOpen(false);setInviteCard(null);setUsersOpen(true);await loadUsers();};
 const createUser=async e=>{e.preventDefault();setAdminError('');try{const r=await request('/admin/users',{method:'POST',body:JSON.stringify(newUser)});setInviteCard(r);setNewUser({name:'',email:'',role:'user'});loadUsers();}catch(e){setAdminError(e.message);}};
 const regenerate=async item=>{if(!confirm(`Vytvořit nový jednorázový QR a odkaz pro ${item.name}? Předchozí pozvánka přestane fungovat.`))return;try{setInviteCard(await request(`/admin/users/${encodeURIComponent(item.id)}/regenerate-code`,{method:'POST'}));loadUsers();}catch(e){setAdminError(e.message);}};
 const updateUser=async item=>{try{await request(`/admin/users/${encodeURIComponent(item.id)}`,{method:'PUT',body:JSON.stringify({name:item.name,role:item.role,active:Boolean(item.active)})});loadUsers();}catch(e){setAdminError(e.message);}};
 const forceLogout=async item=>{if(!confirm(`Odhlásit ${item.name} ze všech zařízení? Účet zůstane zachovaný.`))return;try{await request(`/admin/users/${encodeURIComponent(item.id)}/logout`,{method:'POST'});await loadUsers();}catch(e){setAdminError(e.message);}};
 const deleteUser=async item=>{if(!confirm(`Opravdu trvale smazat uživatele ${item.name}? Bude odhlášen ze všech zařízení a zmizí ze seznamu.`))return;try{await request(`/admin/users/${encodeURIComponent(item.id)}`,{method:'DELETE'});if(inviteCard?.user?.id===item.id)setInviteCard(null);await loadUsers();}catch(e){setAdminError(e.message);}};
 const currentInviteLink=inviteCard?inviteLink(inviteCard.user.email,inviteCard.accessCode):'';
 const inviteQr=useMemo(()=>currentInviteLink?qrSvg(currentInviteLink):'',[currentInviteLink]);
 const copyInvite=async()=>{await navigator.clipboard.writeText(currentInviteLink);alert('Jednorázový přihlašovací odkaz byl zkopírován.');};
 const shareInvite=async()=>{if(!inviteCard)return;const text=`Ahoj, otevři tento jednorázový odkaz pro automatické přihlášení do DFM:\n${currentInviteLink}`;if(navigator.share)await navigator.share({title:'Pozvánka do DFM',text,url:currentInviteLink});else{await navigator.clipboard.writeText(text);alert('Pozvánka byla zkopírována.');}};

 const loadChat=async()=>{if(!navigator.onLine)return;try{setMessages((await request('/chat')).messages||[]);}catch{}};
 useEffect(()=>{if(!chatOpen)return;loadChat();const i=setInterval(loadChat,5000);return()=>clearInterval(i);},[chatOpen,token]);
 const sendMessage=async e=>{e.preventDefault();if(!navigator.onLine){alert('Chat vyžaduje internet.');return;}await request('/chat',{method:'POST',body:JSON.stringify({message:message.trim()})});setMessage('');loadChat();};

 if(auth==='checking')return <div className="auth-screen"><div className="auth-card auth-loading"><div className="auth-logo">DFM</div><p>{location.hash.startsWith('#invite=')?'Přihlašuji z pozvánky…':'Ověřuji přihlášení…'}</p></div></div>;
 if(auth==='offline')return <div className="auth-screen"><section className="auth-card"><div className="auth-logo">DFM</div><h1>První přihlášení vyžaduje internet</h1><button onClick={()=>location.reload()}>Zkusit znovu</button></section></div>;
 if(auth==='activate')return <div className="auth-screen"><section className="auth-card"><div className="auth-logo">DFM</div><p className="auth-kicker">Dokončení účtu</p><h1>Nastavte si PIN</h1><p className="auth-help">Tento šestimístný PIN použijete při prvním spuštění aplikace z plochy.</p><form onSubmit={activate}><label>Firemní e-mail<input value={activation?.email||''} readOnly/></label><label>Nový PIN<input className="pin-input" type="password" inputMode="numeric" autoComplete="new-password" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="••••••" minLength="6" maxLength="6" required/></label><label>PIN znovu<input className="pin-input" type="password" inputMode="numeric" autoComplete="new-password" value={pin2} onChange={e=>setPin2(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="••••••" minLength="6" maxLength="6" required/></label>{error&&<p className="auth-error">{error}</p>}<button disabled={busy}>{busy?'Aktivuji účet…':'Aktivovat účet'}</button></form></section></div>;
 if(auth==='login')return <div className="auth-screen"><section className="auth-card"><div className="auth-logo">DFM</div><p className="auth-kicker">Drone Fleet Manager</p><h1>{initialized?'Přihlášení':'První spuštění'}</h1><form onSubmit={login}>{!initialized&&<label>Jméno<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>Firemní e-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="jmeno@dronetech.cz" required/></label>{initialized&&loginMode==='password'?<label>Administrátorské heslo<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>:<label>{initialized?(pinAuth?'Šestimístný PIN':'Jednorázový přístupový kód'):'Startovací kód'}<input className="pin-input" type={initialized&&pinAuth?'password':'text'} inputMode={initialized&&pinAuth?'numeric':undefined} value={code} onChange={e=>setCode(initialized&&pinAuth?e.target.value.replace(/\D/g,'').slice(0,6):e.target.value.toUpperCase())} placeholder={initialized?(pinAuth?'••••••':'ABCD-EFGH'):'ABCD-EFGH'} minLength={initialized&&pinAuth?6:undefined} maxLength={initialized&&pinAuth?6:undefined} required/></label>}{error&&<p className="auth-error">{error}</p>}<button disabled={busy}>{busy?'Přihlašuji…':initialized?'Přihlásit se':'Vytvořit administrátora'}</button></form>{initialized&&<button className="auth-switch" onClick={()=>{setLoginMode(loginMode==='code'?'password':'code');setError('');setCode('');setPassword('')}}>{loginMode==='code'?'Přihlásit se jako admin heslem':pinAuth?'Použít uživatelský PIN':'Použít jednorázový kód'}</button>}</section></div>;

 const permissions=ROLE_PERMISSIONS[user?.role]||ROLE_PERMISSIONS.user;
 return <><AppV2 permissions={permissions}/><button className="cloud-status" onClick={syncNow}>{status}</button><button className="user-chip" onClick={()=>setProfileOpen(v=>!v)}><span>{user?.name?.[0]||'U'}</span><div><strong>{user?.name}</strong><small>{roleLabel(user?.role)}</small></div></button><button className="chat-fab" onClick={()=>setChatOpen(true)}>💬</button>
 {profileOpen&&<aside className="profile-menu"><strong>{user?.name}</strong><span>{user?.email}</span><em>{roleLabel(user?.role)}</em>{user?.role==='admin'&&<><button onClick={()=>setPasswordOpen(true)}>{user?.hasPassword?'Změnit admin heslo':'Nastavit admin heslo'}</button><button onClick={openUsers}>Správa uživatelů</button></>}<button onClick={logout}>Odhlásit se</button></aside>}
 {passwordOpen&&<div className="chat-overlay"><form className="password-panel" onSubmit={saveAdminPassword}><header><h2>{user?.hasPassword?'Změnit admin heslo':'Nastavit admin heslo'}</h2><button type="button" onClick={()=>setPasswordOpen(false)}>×</button></header><p>Toto heslo slouží jako nouzový přístup pro administrátora na novém zařízení.</p><label>Nové heslo<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} minLength="10" required/></label><label>Heslo znovu<input type="password" value={password2} onChange={e=>setPassword2(e.target.value)} minLength="10" required/></label>{adminError&&<p className="auth-error">{adminError}</p>}<button>Uložit heslo</button></form></div>}
 {usersOpen&&<div className="chat-overlay"><section className="users-panel"><header><div><small>Administrace</small><h2>Uživatelé</h2></div><button onClick={()=>setUsersOpen(false)}>×</button></header><div className="users-content"><form className="invite-form" onSubmit={createUser}><h3>Přidat uživatele</h3><input value={newUser.name} onChange={e=>setNewUser({...newUser,name:e.target.value})} placeholder="Jméno" required/><input type="email" value={newUser.email} onChange={e=>setNewUser({...newUser,email:e.target.value})} placeholder="jmeno@dronetech.cz" required/><select value={newUser.role} onChange={e=>setNewUser({...newUser,role:e.target.value})}><option value="user">Uživatel</option><option value="pilot">Pilot</option><option value="technician">Technik</option><option value="admin">Administrátor</option></select><button>Vytvořit pozvánku</button></form>
 {inviteCard&&<div className="link-invite"><h3>{inviteCard.user.name}</h3><span>{inviteCard.user.email}</span><p>QR nebo odkaz slouží k jednorázové aktivaci účtu a nastavení vlastního šestimístného PINu.</p><div className="invite-qr" dangerouslySetInnerHTML={{__html:inviteQr}}/><input readOnly value={currentInviteLink}/><div><button onClick={copyInvite}>Kopírovat odkaz</button><button onClick={shareInvite}>Sdílet pozvánku</button></div></div>}{adminError&&<p className="auth-error">{adminError}</p>}
 <div className="users-list">{users.map(item=><article key={item.id}><input value={item.name} onChange={e=>setUsers(xs=>xs.map(x=>x.id===item.id?{...x,name:e.target.value}:x))}/><span>{item.email}</span><small className={Number(item.sessions||0)>0?'session-on':'session-off'}>{Number(item.sessions||0)>0?`Přihlášen · ${item.sessions} zařízení`:'Odhlášen · 0 zařízení'}{item.invite_ready?' · pozvánka připravena':''}{item.role==='admin'&&item.has_password?' · heslo nastaveno':''}</small><select value={item.role} onChange={e=>setUsers(xs=>xs.map(x=>x.id===item.id?{...x,role:e.target.value}:x))}><option value="user">Uživatel</option><option value="pilot">Pilot</option><option value="technician">Technik</option><option value="admin">Administrátor</option></select><label><input type="checkbox" checked={Boolean(item.active)} onChange={e=>setUsers(xs=>xs.map(x=>x.id===item.id?{...x,active:e.target.checked?1:0}:x))}/> Aktivní</label><div className="user-actions"><button onClick={()=>updateUser(item)}>Uložit</button><button onClick={()=>regenerate(item)}>Nový QR / odkaz</button><button onClick={()=>forceLogout(item)}>Odhlásit zařízení</button><button className="delete-user" onClick={()=>deleteUser(item)}>Smazat uživatele</button></div></article>)}</div></div></section></div>}
 {chatOpen&&<div className="chat-overlay"><section className="chat-panel"><header><div><small>Společná místnost</small><h2>DFM Chat</h2></div><button onClick={()=>setChatOpen(false)}>×</button></header><div className="chat-messages">{messages.map(x=><article key={x.id}><strong>{x.author}</strong><p>{x.message}</p><time>{new Date(x.created_at+'Z').toLocaleString('cs-CZ')}</time></article>)}</div><form onSubmit={sendMessage}><textarea value={message} onChange={e=>setMessage(e.target.value)} required/><button>Odeslat</button></form></section></div>}</>;
}

